### ISSUE TITLE
US F 18 - Path Creation

### ISSUE THREAD

**Issue by Jonathanbees** [QuitoTactico/SoftServe-Academy#2]
- *Description:* As a content manager, I want to create and curate learning paths by combining different educational resources.
- *Acceptance Criteria:*
  - Managers can combine various resources into a cohesive learning path.
  - Paths are saved and can be shared with users.
- *Tasks:*
  - Design the learning path

 creation interface.
  - Implement functionality to combine and organize resources.
  - Set up storage and retrieval of learning paths.
- *Effort Estimation:* 10 hours

**Comment by QuitoTactico** [comment]
(Sprint 1) They are already autogenerated by the user preferences and target skills, but they cannot be created by the content managers (A.K.A superusers)

**Comment by QuitoTactico** [comment]
Will NOT BE FULLY completed, you will not be able to share your route.

To maintain our vision for the platform, all learning paths are designed to be private and user-specific, rather than publicly accessible or shareable with others. The purpose is to foster a highly personalized learning experience where each user can create their own tailored paths, instead of relying on curated routes from other users, including administrators or certified contributors

Our goal is for users to build unique routes that reflect their individual preferences, availability, and needs, rather than using paths created externally. Although users will still have access to generate and customize their own learning paths, they will not be able to make these public or share them for others to copy or have suggested to them. This approach aligns with our commitment to providing a deeply personal and autonomous learning journey for everyone on the platform
